include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
